Repository swciitg/django_hacktober_2022, pull requests merged in 2022-10, with the labels that each got.

#10 added_models
  sac_management_system/db.sqlite3
  sac_management_system/rooms/admin.py
  sac_management_system/rooms/models.py
  sac_management_system/sac_management_system/settings.py
  sac_management_system/student/admin.py
  sac_management_system/student/models.py
Labels: good first issue, hacktoberfest, SWC, IIT Guwahati, hacktoberfest-accepted, django

#15 Added Home Page
  frontend/package-lock.json
  frontend/package.json
  frontend/public/index.html
  frontend/public/logo192.png
  frontend/public/logo512.png
  frontend/public/robots.txt
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/App.test.js
  frontend/src/Components/CollectionRow.js
  frontend/src/Components/Header.css
  frontend/src/Components/Header.js
  frontend/src/Components/Home.css
  frontend/src/Components/Home.js
  frontend/src/Components/Row.css
  frontend/src/Components/Row.js
  frontend/src/Components/StatusBar.css
  frontend/src/Components/StatusBar.js
  frontend/src/index.css
  frontend/src/index.js
  frontend/src/logo.svg
  frontend/src/reportWebVitals.js
  frontend/src/setupTests.js
Labels: hacktoberfest, SWC, IIT Guwahati, react, hacktoberfest-accepted

#16 Bring test branch up to date
  CONTRIBUTION.md
  README.md
  frontend/.gitignore
  frontend/README.md
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/public/index.html
  frontend/public/manifest.json
  frontend/src/App.css
  frontend/src/App.js
  frontend/src/Components/CollectionRow.js
  frontend/src/Components/Header.css
  frontend/src/Components/Header.js
  frontend/src/Components/Home.css
  frontend/src/Components/Home.js
  frontend/src/Components/Row.css
  frontend/src/Components/Row.js
  frontend/src/Components/StatusBar.css
  frontend/src/Components/StatusBar.js
  frontend/src/index.css
  frontend/src/index.js
  sac_management_system/README.md
  sac_management_system/db.sqlite3
  sac_management_system/requirements.txt
  sac_management_system/rooms/admin.py
  sac_management_system/rooms/models.py
  sac_management_system/sac_management_system/settings.py
  sac_management_system/sac_management_system/urls.py
  sac_management_system/student/admin.py
  sac_management_system/student/models.py
  sac_management_system/users/__init__.py
  sac_management_system/users/admin.py
  sac_management_system/users/apps.py
  sac_management_system/users/forms.py
  sac_management_system/users/models.py
  sac_management_system/users/templates/users/index.html
  sac_management_system/users/templates/users/login.html
  sac_management_system/users/templates/users/logout.html
  sac_management_system/users/templates/users/register.html
  sac_management_system/users/tests.py
  sac_management_system/users/views.py
Labels: hacktoberfest, SWC, IIT Guwahati, react, hacktoberfest-accepted, django

#19 Update README.md
  README.md
Labels: hacktoberfest-accepted

#20 Added Phone number field
  sac_management_system/rooms/models.py
Labels: hacktoberfest, SWC, IIT Guwahati, hacktoberfest-accepted, django

#21 Solved issue
  sac_management_system/rooms/models.py
Labels: hacktoberfest, SWC, IIT Guwahati, hacktoberfest-accepted, django
